id: I5B6294A6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T07:09:33+00:00'
last_modified: '2022-06-08T17:13:42.124105+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ8008
  title: ཐང་སན་ལམ་ཡིག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B433:
      image_group_id: I1PD107023
      title: ''
      total_pages: 23
      order: 1
      base_file: B433.txt
    CA0E:
      image_group_id: I1PD107024
      title: ''
      total_pages: 87
      order: 2
      base_file: CA0E.txt
    '1272':
      image_group_id: I1PD107025
      title: ''
      total_pages: 306
      order: 3
      base_file: 1272.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
