id: I5B6294A6
legacy_id: P010746
ocr_import_info:
  bdrc_scan_id: W2CZ8008
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T07:07:15'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:43:09.177573+00:00'
last_modified: 2022-09-02 23:44:02.410507
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ8008
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ8008
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཐང་སན་ལམ་ཡིག
  author: མི་དབང་མགོན་པོ་སྐྱབས།
statistics:
  ocr_word_mean_confidence_index: 0.776448395855457
  ocr_word_median_confidence_index: 0.8700000047683716
quality: null
bases:
  I1PD107025:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD107025
      total_pages: 306
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1PD107025.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6730815641019262
    legacy_id: v003
  I1PD107023:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD107023
      total_pages: 23
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD107023.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9105993678652398
    legacy_id: v001
  I1PD107024:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD107024
      total_pages: 87
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1PD107024.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.7918120078875499
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
